# -*- coding: utf-8 -*-
"""AURA Assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEoOCeUisXc-8FiSCXbN1DTIE4uaJ3Jl
"""

import os

os.makedirs('.streamlit', exist_ok=True)

# Memperbaiki format string agar valid secara TOML dan Python
# Pastikan private_key menggunakan literal string format (\n) atau triple quotes TOML
secrets_content = r'''GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_DISINI"
TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"

[gcp_service_account]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_DISINI\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@email.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your-cert-url"'''

with open('.streamlit/secrets.toml', 'w') as f:
    f.write(secrets_content)

print('File .streamlit/secrets.toml berhasil diperbaiki! Silakan isi data Anda dan jalankan ulang cell utama.')

import os

# 1. Jalankan instalasi di lingkungan Colab (Bukan di dalam file app.py)
!pip install -q streamlit google-generativeai gspread oauth2client pandas requests

# 2. Tulis kode ke file app.py (PASTIKAN TIDAK ADA !pip DI SINI)
app_code = r'''
import streamlit as st
import google.generativeai as genai
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime
import urllib.parse
import requests

st.set_page_config(page_title="AURA Umrah Assistant", page_icon="\u1332B", layout="centered")

try:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
except Exception as e:
    st.error("Gagal memuat API Key dari secrets.toml.")

system_instruction = """
Anda adalah AURA (Asisten Umrah Ramah & Amanah), representasi virtual dari biro perjalanan Umrah & Haji terpercaya.
Gaya bahasa Anda: Sangat ramah, Islami (salam, masyaAllah, alhamdulillah), sopan, dan profesional.
"""

model = genai.GenerativeModel('gemini-1.5-flash', system_instruction=system_instruction)

def connect_to_sheets():
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    creds_dict = dict(st.secrets["gcp_service_account"])
    creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
    client = gspread.authorize(creds)
    spreadsheet_id = "ID_SPREADSHEET_ANDA_DISINI"
    if spreadsheet_id == "ID_SPREADSHEET_ANDA_DISINI":
        st.error("Silakan ganti ID_SPREADSHEET_ANDA_DISINI dengan ID asli.")
        return None
    return client.open_by_key(spreadsheet_id).sheet1

def send_telegram_notif(nama, paket, no_hp):
    token = st.secrets.get("TELEGRAM_BOT_TOKEN", "")
    chat_id = st.secrets.get("TELEGRAM_CHAT_ID", "")
    pesan = f"Pendaftar Baru: {nama} - {paket}"
    url = f"https://api.telegram.org/bot{token}/sendMessage?chat_id={chat_id}&text={pesan}"
    if token: requests.get(url)

st.title("AURA Assistant")
tab1, tab2 = st.tabs(["Chat", "Pendaftaran"])

with tab1:
    if "messages" not in st.session_state: st.session_state.messages = []
    for m in st.session_state.messages: st.chat_message(m["role"]).markdown(m["content"])
    if prompt := st.chat_input():
        st.chat_message("user").markdown(prompt)
        st.session_state.messages.append({"role": "user", "content": prompt})
        response = model.start_chat().send_message(prompt)
        st.chat_message("assistant").markdown(response.text)
        st.session_state.messages.append({"role": "assistant", "content": response.text})

with tab2:
    with st.form("reg"):
        nama = st.text_input("Nama")
        no_hp = st.text_input("WA")
        paket = st.selectbox("Paket", ["Umrah Reguler", "Umrah Plus"])
        if st.form_submit_button("Daftar"):
            if nama and no_hp:
                try:
                    sheet = connect_to_sheets()
                    if sheet:
                        sheet.append_row([nama, no_hp, paket, str(datetime.now())])
                        send_telegram_notif(nama, paket, no_hp)
                        st.success("Berhasil!")
                except Exception as e: st.error(str(e))
'''

with open('app.py', 'w') as f:
    f.write(app_code)

print("File app.py berhasil diperbarui. Perintah !pip sudah dipindahkan ke luar file!")

requirements = '''
streamlit
google-generativeai
gspread
oauth2client
pandas
requests
'''

with open('requirements.txt', 'w') as f:
    f.write(requirements.strip())

print('File requirements.txt berhasil dibuat! Pastikan file ini ikut di-upload ke GitHub Anda.')

import os

# Kode aplikasi yang sudah bersih dan benar
final_code = r'''
import streamlit as st
import google.generativeai as genai
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime
import urllib.parse
import requests

st.set_page_config(page_title="AURA Umrah Assistant", page_icon="\u1332B", layout="centered")

try:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
except Exception as e:
    st.error("Gagal memuat API Key.")

system_instruction = """
Anda adalah AURA (Asisten Umrah Ramah & Amanah), representasi virtual dari biro perjalanan Umrah & Haji terpercaya.
Gaya bahasa Anda: Sangat ramah, Islami (salam, masyaAllah, alhamdulillah), sopan, dan profesional.
"""

model = genai.GenerativeModel('gemini-1.5-flash', system_instruction=system_instruction)

def connect_to_sheets():
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    creds_dict = dict(st.secrets["gcp_service_account"])
    creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
    client = gspread.authorize(creds)
    spreadsheet_id = "ID_SPREADSHEET_ANDA_DISINI"
    if spreadsheet_id == "ID_SPREADSHEET_ANDA_DISINI":
        st.error("Silakan isi ID Spreadsheet Anda di kode ini.")
        return None
    return client.open_by_key(spreadsheet_id).sheet1

st.title("AURA Assistant")
tab1, tab2 = st.tabs(["Chat", "Pendaftaran"])

with tab1:
    if "messages" not in st.session_state: st.session_state.messages = []
    for m in st.session_state.messages: st.chat_message(m["role"]).markdown(m["content"])
    if prompt := st.chat_input("Tanya AURA..."):
        st.chat_message("user").markdown(prompt)
        st.session_state.messages.append({"role": "user", "content": prompt})
        response = model.start_chat().send_message(prompt)
        st.chat_message("assistant").markdown(response.text)
        st.session_state.messages.append({"role": "assistant", "content": response.text})

with tab2:
    with st.form("reg_form"):
        nama = st.text_input("Nama")
        no_hp = st.text_input("WhatsApp (628...)")
        paket = st.selectbox("Pilihan Paket", ["Umrah Reguler", "Umrah Plus", "Haji Furoda"])
        if st.form_submit_button("Kirim Pendaftaran"):
            if nama and no_hp:
                try:
                    sheet = connect_to_sheets()
                    if sheet:
                        sheet.append_row([nama, no_hp, paket, str(datetime.now())])
                        st.success("Pendaftaran Berhasil Dikirim!")
                except Exception as e: st.error(f"Gagal: {e}")
'''

# Simpan ke kedua nama file agar tidak bingung
with open('aura_assistant.py', 'w') as f:
    f.write(final_code)

with open('app.py', 'w') as f:
    f.write(final_code)

print('BERHASIL: File aura_assistant.py dan app.py sekarang identik dan sudah diperbaiki!')

import urllib
print("Password/Enpoint IP untuk LocalTunnel Anda adalah:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

# Menjalankan streamlit di background dan membukanya via localtunnel
!streamlit run app.py & npx localtunnel --port 8501