# -*- coding: utf-8 -*-
"""AURA Assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEoOCeUisXc-8FiSCXbN1DTIE4uaJ3Jl
"""

import os

os.makedirs('.streamlit', exist_ok=True)

# Memperbaiki format string agar valid secara TOML dan Python
# Pastikan private_key menggunakan literal string format (\n) atau triple quotes TOML
secrets_content = r'''GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_DISINI"
TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"

[gcp_service_account]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_DISINI\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@email.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your-cert-url"'''

with open('.streamlit/secrets.toml', 'w') as f:
    f.write(secrets_content)

print('File .streamlit/secrets.toml berhasil diperbaiki! Silakan isi data Anda dan jalankan ulang cell utama.')

requirements = '''
streamlit
google-generativeai
gspread
oauth2client
pandas
requests
'''

with open('requirements.txt', 'w') as f:
    f.write(requirements.strip())

print('File requirements.txt BERHASIL diperbarui!')
print('Isi file:')
print('---')
with open('requirements.txt', 'r') as f:
    print(f.read())
print('---')
print('SILAKAN SALIN TEKS DI ATAS KE GITHUB ANDA.')

import urllib
print("Password/Endpoint IP untuk LocalTunnel Anda adalah:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

# Menjalankan Streamlit dan LocalTunnel
# Kita gunakan app.py sebagai file utama
!streamlit run app.py & npx localtunnel --port 8501

import os

# Kode aplikasi versi paling stabil menggunakan Sidebar Navigation
final_code = r'''
import streamlit as st
import google.generativeai as genai
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime
import requests

# Pengaturan halaman yang stabil
st.set_page_config(page_title="AURA Assistant", page_icon="\u1332B", layout="wide")

# Load Secrets
try:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
except Exception:
    st.warning("API Key tidak terdeteksi di secrets.")

system_instruction = "Anda adalah AURA, Asisten Umrah Ramah & Amanah."
model = genai.GenerativeModel('gemini-1.5-flash', system_instruction=system_instruction)

def connect_to_sheets():
    try:
        scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
        creds_dict = dict(st.secrets["gcp_service_account"])
        creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
        client = gspread.authorize(creds)
        return client.open_by_key("ID_SPREADSHEET_ANDA_DISINI").sheet1
    except Exception as e:
        st.error(f"Koneksi Google Sheets gagal. Pastikan ID dan Kredensial benar.")
        return None

# Navigasi Sidebar - Jauh lebih stabil dibanding Tabs
st.sidebar.title("\u1332B AURA Menu")
page = st.sidebar.radio("Pindah Halaman:", ["Chat AI", "Pendaftaran"])

if page == "Chat AI":
    st.title("Tanya AURA")
    if "messages" not in st.session_state:
        st.session_state.messages = []

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if prompt := st.chat_input("Ketik pesan Anda di sini..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        response = model.start_chat().send_message(prompt)
        with st.chat_message("assistant"):
            st.markdown(response.text)
        st.session_state.messages.append({"role": "assistant", "content": response.text})

elif page == "Pendaftaran":
    st.title("Form Pendaftaran")
    with st.form("pendaftaran_form", clear_on_submit=True):
        nama = st.text_input("Nama Lengkap")
        wa = st.text_input("Nomor WhatsApp (62...)")
        paket = st.selectbox("Pilih Paket", ["Umrah Reguler", "Umrah Plus", "Haji Furoda"])

        if st.form_submit_button("Daftar Sekarang"):
            if nama and wa:
                sheet = connect_to_sheets()
                if sheet:
                    sheet.append_row([nama, wa, paket, str(datetime.now())])
                    st.success("Alhamdulillah! Data berhasil terkirim.")
            else:
                st.error("Mohon lengkasi semua data.")
'''

with open('app.py', 'w') as f:
    f.write(final_code)

with open('aura_assistant.py', 'w') as f:
    f.write(final_code)

print("PERBAIKAN SELESAI: Gunakan kode ini untuk memperbaiki error 'removeChild'!")