# -*- coding: utf-8 -*-
"""AURA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1QDpLDIavG9zQ--XUvjYUuOsWbL_ZIL
"""

import google.generativeai as genai
from google.colab import userdata

# 1. Konfigurasi API Key
try:
    API_KEY = userdata.get('GOOGLE_API_KEY')
    if API_KEY:
        genai.configure(api_key=API_KEY)
    else:
        print("⚠️ API Key tidak ditemukan di Colab Secrets.")
except Exception as e:
    print(f"⚠️ Gagal: {e}")

def generate_respon_aura(nama_jamaah, paket_pilihan):
    instruksi_sistem = "Nama Anda adalah AURA. Sapa hangat dan jelaskan paket."
    try:
        # Menggunakan identifier yang terkonfirmasi ada di list_models()
        model = genai.GenerativeModel(
            model_name='gemini-flash-latest',
            system_instruction=instruksi_sistem
        )
        response = model.generate_content(f"{nama_jamaah} tanya {paket_pilihan}")
        return response.text
    except Exception as e:
        return f"Terjadi kesalahan: {str(e)}"

if API_KEY:
    print("--- Percobaan Respon ---")
    print(generate_respon_aura("Budi", "Umrah Plus Turki"))

"""### 🕋 AURA Interactive Consultant
Gunakan panel di bawah ini untuk mensimulasikan percakapan dengan jamaah.
"""

import ipywidgets as widgets
from IPython.display import display, clear_output
from datetime import datetime
import re

# Widget Input
nama_input = widgets.Text(description="Nama:", placeholder="Masukkan nama jamaah")
telepon_input = widgets.Text(description="No. WA:", placeholder="Contoh: 08123456789")
email_input = widgets.Text(description="Email:", placeholder="(Opsional) contoh@mail.com")
alamat_input = widgets.Text(description="Alamat/Kota:", placeholder="Masukkan kota asal")
paket_dropdown = widgets.Dropdown(
    options=["Paket Umrah Reguler (9 Hari)", "Paket Umrah Plus Turki (12 Hari)", "Paket Haji Furoda"],
    description="Paket:",
    value="Paket Umrah Reguler (9 Hari)"
)
tombol_generate = widgets.Button(description="Tanya AURA", button_style='primary')
output_area = widgets.Output()

def is_valid_email(email):
    """Fungsi untuk validasi format email"""
    if not email.strip():
        return True  # Karena opsional
    pola = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return re.match(pola, email) is not None

def kirim_notifikasi_email(nama, telepon, email, alamat, paket):
    """Simulasi pengiriman email ke Admin"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    email_val = email if email.strip() else "Tidak dicantumkan"
    subjek = f"[NOTIFIKASI AURA] Jamaah Baru: {nama}"
    pesan = f"Halo Admin,\n\nAda jamaah baru yang baru saja berkonsultasi:\nNama: {nama}\nNo. Telp: {telepon}\nEmail: {email_val}\nAlamat: {alamat}\nPaket: {paket}\nWaktu: {timestamp}\n\nSegera cek riwayat chat untuk detail lebih lanjut."

    print(f"\n[EMAIL SENT] To: admin@travelumrah.com")
    print(f"Subject: {subjek}")

    with open("log_email_notifikasi.txt", "a", encoding="utf-8") as f:
        f.write(f"\n--- Email Notifikasi ---\nTo: admin@travelumrah.com\n{pesan}\n{'-'*30}\n")

def simpan_ke_file(nama, telepon, email, alamat, paket, respon):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    email_val = email if email.strip() else "-"
    with open("riwayat_chat_aura.txt", "a", encoding="utf-8") as f:
        f.write(f"\n{'='*50}\n")
        f.write(f"Waktu: {timestamp}\n")
        f.write(f"Jamaah: {nama} ({telepon})\n")
        f.write(f"Email: {email_val} | Kota: {alamat}\n")
        f.write(f"Paket: {paket}\n")
        f.write(f"Respon AURA:\n{respon}\n")
        f.write(f"{'='*50}\n")

def on_button_clicked(b):
    with output_area:
        clear_output()

        # Validasi Input
        if not nama_input.value.strip():
            print("⚠️ Peringatan: Silakan masukkan nama jamaah.")
            return
        if not telepon_input.value.strip() or len(telepon_input.value.strip()) < 10:
            print("⚠️ Peringatan: Silakan masukkan nomor WhatsApp yang valid (min. 10 digit).")
            return
        if not is_valid_email(email_input.value):
            print("⚠️ Peringatan: Format email tidak valid. Silakan periksa kembali atau kosongkan jika tidak ada.")
            return
        if not alamat_input.value.strip():
            print("⚠️ Peringatan: Silakan masukkan alamat atau kota asal.")
            return

        print(f"Sedang menghubungi AURA untuk {nama_input.value} dari {alamat_input.value}...\n")
        respon = generate_respon_aura(nama_input.value, paket_dropdown.value)
        print(respon)

        # Simpan riwayat & Kirim Notifikasi
        try:
            simpan_ke_file(nama_input.value, telepon_input.value, email_input.value, alamat_input.value, paket_dropdown.value, respon)
            kirim_notifikasi_email(nama_input.value, telepon_input.value, email_input.value, alamat_input.value, paket_dropdown.value)
            print(f"\n[Sistem: Data {nama_input.value} berhasil diproses & Notifikasi dikirim]")
        except Exception as e:
            print(f"\n[Gagal memproses data: {str(e)}]")

tombol_generate.on_click(on_button_clicked)

# Tampilkan UI
display(nama_input, telepon_input, email_input, alamat_input, paket_dropdown, tombol_generate, output_area)

"""### 📥 Download Riwayat
Gunakan tombol di bawah ini jika ingin mengunduh file `riwayat_chat_aura.txt`.
"""

from google.colab import files
import os

tombol_download = widgets.Button(description="Unduh Riwayat (.txt)", button_style='success')
out_dl = widgets.Output()

def download_file(b):
    with out_dl:
        if os.path.exists("riwayat_chat_aura.txt"):
            files.download("riwayat_chat_aura.txt")
            print("File sedang diunduh...")
        else:
            print("Belum ada riwayat chat yang tersimpan.")

tombol_download.on_click(download_file)
display(tombol_download, out_dl)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# google-generativeai
# ipywidgets

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import google.generativeai as genai
# import os
# from datetime import datetime
# 
# # Konfigurasi Halaman
# st.set_page_config(page_title="AURA - Umrah Assistant", page_icon="🕋")
# 
# # Setup Gemini dari Secrets
# try:
#     API_KEY = st.secrets["GOOGLE_API_KEY"]
#     genai.configure(api_key=API_KEY)
# except Exception as e:
#     st.error("API Key tidak ditemukan di Secrets.")
#     st.stop()
# 
# def generate_respon_aura(nama_jamaah, paket_pilihan):
#     instruksi_sistem = "Nama Anda adalah AURA (AI-Powered Umrah Responsive Assistant). Sapa hangat dan arahkan ke https://wa.me/6281252539170"
#     try:
#         # Menggunakan identifier gemini-flash-latest
#         model = genai.GenerativeModel('gemini-flash-latest', system_instruction=instruksi_sistem)
#         response = model.generate_content(f"{nama_jamaah} bertanya tentang {paket_pilihan}")
#         return response.text
#     except Exception as e:
#         return f"Maaf, gangguan koneksi AI: {str(e)}"
# 
# st.title("🕋 AURA Assistant")
# 
# with st.form("aura_form"):
#     nama = st.text_input("Nama Lengkap")
#     wa = st.text_input("Nomor WhatsApp")
#     paket = st.selectbox("Pilih Paket", ["Umrah Reguler", "Umrah Plus Turki", "Haji Furoda"])
#     submitted = st.form_submit_button("Tanya AURA")
# 
# if submitted:
#     if nama and wa:
#         with st.spinner("Menghubungi AURA..."):
#             st.markdown(generate_respon_aura(nama, paket))
#     else:
#         st.error("Mohon isi Nama dan Nomor WhatsApp.")

"""### 🚀 Menjalankan Aplikasi Streamlit
1. Jalankan sel di bawah ini.
2. Klik link yang muncul di sebelah tulisan `your url is:`.
3. Jika diminta 'Endpoint IP', masukkan alamat IP publik Colab (akan muncul di output sel).
"""

!pip install -q streamlit
!npm install -q -g localtunnel
import urllib
print("Password/Endpoint IP untuk localtunnel:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())
!streamlit run app.py & npx localtunnel --port 8501

"""### 📊 Integrasi Google Sheets
Ikuti langkah ini untuk menghubungkan data ke Google Sheets:
1. Instal `gspread`.
2. Siapkan kredensial Service Account (`credentials.json`).
3. Gunakan kode di bawah ini di dalam `app.py`.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile -a requirements.txt
# gspread
# google-auth

# Contoh snippet kode untuk ditambahkan ke app.py
import gspread
from google.oauth2.service_account import Credentials

def simpan_ke_google_sheets(data_list):
    # Ganti 'credentials.json' dengan file Anda
    scopes = ["https://www.googleapis.com/auth/spreadsheets"]
    creds = Credentials.from_service_account_file("credentials.json", scopes=scopes)
    client = gspread.authorize(creds)

    # Buka spreadsheet berdasarkan Nama atau URL
    sheet = client.open("Data Jamaah AURA").sheet1
    sheet.append_row(data_list)
    print("Data berhasil dikirim ke Google Sheets!")

with open('app.py', 'r') as f:
    print(f.read())

!pip install -q streamlit gspread google-auth
!npm install -q -g localtunnel
import urllib
print("Password/Endpoint IP untuk localtunnel:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())
!streamlit run app.py & npx localtunnel --port 8501