# -*- coding: utf-8 -*-
"""AURA Assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEoOCeUisXc-8FiSCXbN1DTIE4uaJ3Jl
"""

import os

os.makedirs('.streamlit', exist_ok=True)

# Memperbaiki format string agar valid secara TOML dan Python
# Pastikan private_key menggunakan literal string format (\n) atau triple quotes TOML
secrets_content = r'''GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_DISINI"
TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"

[gcp_service_account]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_DISINI\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@email.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your-cert-url"'''

with open('.streamlit/secrets.toml', 'w') as f:
    f.write(secrets_content)

print('File .streamlit/secrets.toml berhasil diperbaiki! Silakan isi data Anda dan jalankan ulang cell utama.')

!pip install streamlit google-generativeai gspread oauth2client pandas requests

import streamlit as st
import google.generativeai as genai
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime
import urllib.parse
import requests

# ==========================================
# KONFIGURASI HALAMAN STREAMLIT
# ==========================================
st.set_page_config(page_title="AURA Umrah Assistant", page_icon="ጲB", layout="centered")

# ==========================================
# INISIALISASI GEMINI API
# ==========================================
try:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
except Exception as e:
    st.error("Gagal memuat API Key dari secrets.toml. Pastikan cell pertama sudah dijalankan dengan data benar.")

# Persona AURA
system_instruction = """
Anda adalah AURA (Asisten Umrah Ramah & Amanah), representasi virtual dari biro perjalanan Umrah & Haji terpercaya.
Gaya bahasa Anda: Sangat ramah, Islami (salam, masyaAllah, alhamdulillah), sopan, dan profesional.
Tujuan utama: Memberikan informasi paket dan mengarahkan jamaah untuk mengisi form pendaftaran di tab 'Form Pendaftaran'.
"""

model = genai.GenerativeModel('gemini-1.5-flash', system_instruction=system_instruction)

# ==========================================
# FUNGSI PEMBANTU
# ==========================================
def connect_to_sheets():
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    creds_dict = dict(st.secrets["gcp_service_account"])
    creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
    client = gspread.authorize(creds)

    # GANTI 'ID_SPREADSHEET_ANDA_DISINI' dengan ID spreadsheet Anda
    spreadsheet_id = "ID_SPREADSHEET_ANDA_DISINI"
    if spreadsheet_id == "ID_SPREADSHEET_ANDA_DISINI":
        st.error("Silakan ganti ID_SPREADSHEET_ANDA_DISINI dengan ID asli di kode Python ini.")
        return None

    sheet = client.open_by_key(spreadsheet_id).sheet1
    return sheet

def send_telegram_notif(nama, paket, no_hp):
    token = st.secrets.get("TELEGRAM_BOT_TOKEN", "YOUR_BOT_TOKEN")
    chat_id = st.secrets.get("TELEGRAM_CHAT_ID", "YOUR_CHAT_ID")
    pesan = f"☑• *Pendaftar Baru AURA*\n\nNama: {nama}\nPaket: {paket}\nWA: https://wa.me/{no_hp}"
    url = f"https://api.telegram.org/bot{token}/sendMessage?chat_id={chat_id}&text={pesan}&parse_mode=Markdown"
    requests.get(url)

# ==========================================
# UI APLIKASI
# ==========================================
st.title("ጲB AURA: Asisten Umrah & Haji Anda")
tab1, tab2 = st.tabs(["ᄒ Chat dengan AURA", "፣ Form Pendaftaran"])

with tab1:
    if "messages" not in st.session_state: st.session_state.messages = []
    for m in st.session_state.messages:
        with st.chat_message(m["role"]): st.markdown(m["content"])

    if prompt := st.chat_input("Tanya AURA tentang paket Umrah..."):
        st.chat_message("user").markdown(prompt)
        st.session_state.messages.append({"role": "user", "content": prompt})
        response = model.start_chat(history=[]).send_message(prompt)
        with st.chat_message("assistant"): st.markdown(response.text)
        st.session_state.messages.append({"role": "assistant", "content": response.text})

with tab2:
    st.header("Formulir Minat Jamaah")
    with st.form("form_pendaftaran"):
        nama = st.text_input("Nama Lengkap")
        email = st.text_input("Email")
        no_hp = st.text_input("Nomor WhatsApp (628...)")
        alamat = st.text_area("Alamat")
        paket = st.selectbox("Pilihan Paket", ["Umrah Reguler", "Umrah Plus", "Haji Furoda"])
        submit = st.form_submit_button("Kirim Data & Chat Admin")

        if submit:
            if nama and no_hp:
                try:
                    sheet = connect_to_sheets()
                    if sheet:
                        sheet.append_row([nama, email, no_hp, alamat, paket, datetime.now().strftime("%Y-%m-%d")])
                        send_telegram_notif(nama, paket, no_hp)
                        admin_phone = "6281252539170"
                        msg = urllib.parse.quote(f"Assalamu'alaikum Admin. Saya {nama} tertarik paket {paket}.")
                        st.success("Data tersimpan! Klik tombol di bawah:")
                        st.markdown(f'[ Hubungi Admin via WhatsApp ](https://wa.me/{admin_phone}?text={msg})')
                except Exception as e: st.error(f"Error: {e}")
            else: st.warning("Lengkapi data!")